from __future__ import annotations

import io
from datetime import datetime
from typing import List


def generate_conversation_pdf(messages: List[dict], company_name: str = "AriaCall") -> bytes:
    """
    Build a PDF transcript from a list of {role, text} dicts.
    Returns raw PDF bytes.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    coral = colors.HexColor("#ff6d4a")
    dark = colors.HexColor("#1a1c23")
    muted = colors.HexColor("#9898a8")
    white = colors.HexColor("#f5f1ea")

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Normal"],
        fontSize=18,
        fontName="Helvetica-Bold",
        textColor=coral,
        spaceAfter=2 * mm,
    )
    subtitle_style = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica",
        textColor=muted,
        spaceAfter=6 * mm,
    )
    user_label = ParagraphStyle(
        "UserLabel",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Helvetica-Bold",
        textColor=coral,
        spaceBefore=4 * mm,
        spaceAfter=1 * mm,
    )
    aria_label = ParagraphStyle(
        "AriaLabel",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Helvetica-Bold",
        textColor=muted,
        spaceBefore=4 * mm,
        spaceAfter=1 * mm,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica",
        leading=15,
        textColor=dark,
    )

    stamp = datetime.now().strftime("%d %B %Y, %H:%M")

    story = [
        Paragraph("ARIA", title_style),
        Paragraph(f"{company_name} · Conversation export · {stamp}", subtitle_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e0ddd8"), spaceAfter=6 * mm),
    ]

    for msg in messages:
        role = msg.get("role", "user")
        text = msg.get("text", msg.get("content", "")).strip()
        if not text:
            continue

        if role == "user":
            story.append(Paragraph("YOU", user_label))
        else:
            story.append(Paragraph("ARIA", aria_label))

        # Escape HTML special chars for ReportLab Paragraph
        safe = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(safe, body_style))

    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e0ddd8")))
    story.append(Paragraph(
        f"Generated by Aria · {company_name} · {stamp}",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=muted, spaceBefore=3 * mm),
    ))

    doc.build(story)
    return buf.getvalue()
